/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Calendars */
        get: operations["list_calendars_calendars_get"];
        put?: never;
        /** Create Calendar */
        post: operations["create_calendar_calendars_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars/{calendar_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calendar */
        get: operations["get_calendar_calendars__calendar_id__get"];
        put?: never;
        post?: never;
        /** Delete Calendar */
        delete: operations["delete_calendar_calendars__calendar_id__delete"];
        options?: never;
        head?: never;
        /** Update Calendar */
        patch: operations["update_calendar_calendars__calendar_id__patch"];
        trace?: never;
    };
    "/calendars/{calendar_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Share Calendar */
        post: operations["share_calendar_calendars__calendar_id__share_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Clients */
        get: operations["search_clients_clients_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{client_id}/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client Agenda */
        get: operations["get_client_agenda_clients__client_id__agenda_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_clients__client_id__get"];
        put?: never;
        post?: never;
        /** Delete Client */
        delete: operations["delete_client_clients__client_id__delete"];
        options?: never;
        head?: never;
        /** Update Client */
        patch: operations["update_client_clients__client_id__patch"];
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_events_get"];
        put?: never;
        /** Create Event */
        post: operations["create_event_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_events__event_id__get"];
        /** Update Event */
        put: operations["update_event_events__event_id__put"];
        post?: never;
        /** Delete Event */
        delete: operations["delete_event_events__event_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/check-conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Conflicts */
        post: operations["check_conflicts_events_check_conflicts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Availability */
        get: operations["get_availability_availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suggestions */
        get: operations["get_suggestions_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Students */
        get: operations["list_students_students_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/reminder-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reminder Settings */
        get: operations["get_reminder_settings_students_reminder_settings_get"];
        /** Update Reminder Settings */
        put: operations["update_reminder_settings_students_reminder_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{client_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student Profile */
        get: operations["get_student_profile_students__client_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Upsert Student Profile */
        patch: operations["upsert_student_profile_students__client_id__profile_patch"];
        trace?: never;
    };
    "/students/{client_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Student Notes */
        get: operations["list_student_notes_students__client_id__notes_get"];
        put?: never;
        /** Add Student Note */
        post: operations["add_student_note_students__client_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_tasks__task_id__patch"];
        trace?: never;
    };
    "/formations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Formations */
        get: operations["list_formations_formations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cron/generate-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Alerts */
        post: operations["generate_alerts_cron_generate_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cron/generate-task-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Task Alerts */
        post: operations["generate_task_alerts_cron_generate_task_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cron/generate-followup-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Followup Alerts */
        post: operations["generate_followup_alerts_cron_generate_followup_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cron/sync-alert-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Alert Sheet */
        post: operations["sync_alert_sheet_cron_sync_alert_sheet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertPriority
         * @enum {string}
         */
        AlertPriority: "normal" | "important" | "urgent";
        /** AlertRead */
        AlertRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Client Id */
            client_id: string | null;
            /** Task Id */
            task_id: string | null;
            alert_type: components["schemas"]["AlertType"];
            priority: components["schemas"]["AlertPriority"];
            /** Message Title */
            message_title: string;
            /** Message Body */
            message_body: string;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            status: components["schemas"]["AlertStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at: string | null;
            /** Sheet Row Id */
            sheet_row_id: string | null;
            /** Make Status */
            make_status: string | null;
        };
        /**
         * AlertStatus
         * @enum {string}
         */
        AlertStatus: "pending" | "sent" | "failed" | "skipped";
        /**
         * AlertType
         * @enum {string}
         */
        AlertType: "progress_check" | "cancelled_appointment_followup" | "appointment_preparation" | "missing_onboarding" | "task_overdue_start" | "stale_followup";
        /** AvailabilityResponse */
        AvailabilityResponse: {
            /** Free Slots */
            free_slots: components["schemas"]["FreeSlot"][];
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /** CalendarCreate */
        CalendarCreate: {
            /** Name */
            name: string;
            /**
             * Color
             * @default #3B82F6
             */
            color: string;
            /** @default personal */
            type: components["schemas"]["CalendarType"];
            /**
             * Default Buffer Min
             * @default 30
             */
            default_buffer_min: number;
        };
        /** CalendarRead */
        CalendarRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Name */
            name: string;
            /** Color */
            color: string;
            type: components["schemas"]["CalendarType"];
            /** Default Buffer Min */
            default_buffer_min: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            role?: components["schemas"]["ShareRole"] | null;
        };
        /**
         * CalendarType
         * @enum {string}
         */
        CalendarType: "personal" | "work" | "team" | "resource";
        /** CalendarUpdate */
        CalendarUpdate: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
            type?: components["schemas"]["CalendarType"] | null;
            /** Default Buffer Min */
            default_buffer_min?: number | null;
        };
        /** CheckConflictsRequest */
        CheckConflictsRequest: {
            /** Calendar Ids */
            calendar_ids: string[];
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
            /**
             * Buffer Min
             * @default 30
             */
            buffer_min: number;
            /** Exclude Event Id */
            exclude_event_id?: string | null;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Nom */
            nom: string;
            /**
             * Prenom
             * @default
             */
            prenom: string;
            /** Email */
            email?: string | null;
            /** Telephone */
            telephone?: string | null;
            /**
             * Color
             * @default #6366f1
             */
            color: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /** Rate Per Hour */
            rate_per_hour?: number | null;
            /** Forfait Hours */
            forfait_hours?: number | null;
            /** @default patron */
            client_type: components["schemas"]["ClientType"];
        };
        /** ClientRead */
        ClientRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Nom */
            nom: string;
            /** Prenom */
            prenom: string;
            /** Email */
            email: string | null;
            /** Telephone */
            telephone: string | null;
            /** Color */
            color: string;
            /** Timezone */
            timezone: string;
            /** Rate Per Hour */
            rate_per_hour: number | null;
            /** Forfait Hours */
            forfait_hours: number | null;
            /** Status */
            status: string;
            client_type: components["schemas"]["ClientType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ClientType
         * @enum {string}
         */
        ClientType: "patron" | "apprenant";
        /** ClientUpdate */
        ClientUpdate: {
            /** Nom */
            nom?: string | null;
            /** Prenom */
            prenom?: string | null;
            /** Email */
            email?: string | null;
            /** Telephone */
            telephone?: string | null;
            /** Color */
            color?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Rate Per Hour */
            rate_per_hour?: number | null;
            /** Forfait Hours */
            forfait_hours?: number | null;
            /** Status */
            status?: ("active" | "inactive") | null;
            client_type?: components["schemas"]["ClientType"] | null;
        };
        /** ConflictDetail */
        ConflictDetail: {
            /**
             * With Event Id
             * Format: uuid
             */
            with_event_id: string;
            type: components["schemas"]["ConflictType"];
            severity: components["schemas"]["ConflictSeverity"];
            /** Observed Gap Min */
            observed_gap_min: number;
        };
        /**
         * ConflictSeverity
         * @enum {string}
         */
        ConflictSeverity: "blocking" | "warning" | "info";
        /**
         * ConflictType
         * @enum {string}
         */
        ConflictType: "overlap" | "insufficient_buffer" | "tight" | "resource_clash";
        /** DashboardResponse */
        DashboardResponse: {
            /** Upcoming Conflicts */
            upcoming_conflicts: Record<string, never>[];
            /** Free Slots Today */
            free_slots_today: components["schemas"]["FreeSlot"][];
            /** Day Scores */
            day_scores: components["schemas"]["DayScore"][];
        };
        /** DayScore */
        DayScore: {
            /** Date */
            date: string;
            /** Score */
            score: number;
            /** Conflicts Count */
            conflicts_count: number;
            /** Events Count */
            events_count: number;
        };
        /** EmailNotVerifiedError */
        EmailNotVerifiedError: {
            /**
             * Detail
             * @constant
             * @enum {string}
             */
            detail: "email_not_verified";
        };
        /** EmailVerifyRequest */
        EmailVerifyRequest: {
            /** Token */
            token: string;
        };
        /** EventCreate */
        EventCreate: {
            /**
             * Calendar Id
             * Format: uuid
             */
            calendar_id: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Billable
             * @default true
             */
            billable: boolean;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
            /**
             * All Day
             * @default false
             */
            all_day: boolean;
            /** Buffer Min */
            buffer_min?: number | null;
            /** @default normal */
            priority: components["schemas"]["EventPriority"];
            /** @default confirmed */
            status: components["schemas"]["EventStatus"];
            /** Rrule */
            rrule?: string | null;
        };
        /** EventCreateResponse */
        EventCreateResponse: {
            event: components["schemas"]["EventRead"];
            /** Conflicts */
            conflicts: components["schemas"]["ConflictDetail"][];
            /** Suggestions */
            suggestions: components["schemas"]["SlotSuggestion"][];
        };
        /**
         * EventPriority
         * @enum {string}
         */
        EventPriority: "low" | "normal" | "high";
        /** EventRead */
        EventRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Calendar Id
             * Format: uuid
             */
            calendar_id: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Billable
             * @default true
             */
            billable: boolean;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Location */
            location: string | null;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
            /** All Day */
            all_day: boolean;
            /** Buffer Min */
            buffer_min: number | null;
            priority: components["schemas"]["EventPriority"];
            status: components["schemas"]["EventStatus"];
            /** Rrule */
            rrule: string | null;
            /** Recurrence Parent Id */
            recurrence_parent_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EventStatus
         * @enum {string}
         */
        EventStatus: "confirmed" | "tentative" | "cancelled";
        /** EventUpdate */
        EventUpdate: {
            /** Client Id */
            client_id?: string | null;
            /** Billable */
            billable?: boolean | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /** Start Utc */
            start_utc?: string | null;
            /** End Utc */
            end_utc?: string | null;
            /** All Day */
            all_day?: boolean | null;
            /** Buffer Min */
            buffer_min?: number | null;
            priority?: components["schemas"]["EventPriority"] | null;
            status?: components["schemas"]["EventStatus"] | null;
            /** Rrule */
            rrule?: string | null;
        };
        /** FormationRead */
        FormationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            category: components["schemas"]["StudentCategory"];
            secondary_category: components["schemas"]["StudentCategory"] | null;
            /** Training Duration Text */
            training_duration_text: string | null;
            /** Study Hours Text */
            study_hours_text: string | null;
            /** Access Duration Text */
            access_duration_text: string | null;
            /** Access Duration Months */
            access_duration_months: number | null;
            /** Price Text */
            price_text: string | null;
            /** Certification Name */
            certification_name: string | null;
            /** Exam Info Text */
            exam_info_text: string | null;
            /** Module Count Text */
            module_count_text: string | null;
            /** Modules Detail */
            modules_detail: string | null;
            /** Csm Note */
            csm_note: string | null;
            /** Source Url */
            source_url: string | null;
        };
        /** FreeSlot */
        FreeSlot: {
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
            /** Duration Min */
            duration_min: number;
        };
        /** GenerateAlertsRequest */
        GenerateAlertsRequest: {
            /** Alert Types */
            alert_types?: components["schemas"]["AlertType"][] | null;
        };
        /** GenerateAlertsResponse */
        GenerateAlertsResponse: {
            /** Created */
            created: components["schemas"]["AlertRead"][];
            /** Skipped Duplicates */
            skipped_duplicates: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvalidCredentialsError */
        InvalidCredentialsError: {
            /**
             * Detail
             * @constant
             * @enum {string}
             */
            detail: "Invalid email or password";
        };
        /** InvalidOrExpiredTokenError */
        InvalidOrExpiredTokenError: {
            /**
             * Detail
             * @constant
             * @enum {string}
             */
            detail: "invalid_or_expired_token";
        };
        /**
         * LearnerStatus
         * @enum {string}
         */
        LearnerStatus: "nouveau" | "actif" | "a_risque" | "examen_prevu" | "diplome" | "suspendu" | "cloture";
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * PaymentStatus
         * @enum {string}
         */
        PaymentStatus: "solde" | "mensualise" | "organisme" | "impaye";
        /**
         * ProgressStatus
         * @enum {string}
         */
        ProgressStatus: "bon_rythme" | "a_surveiller" | "distrait" | "bloque" | "suspendu" | "diplome" | "cloture";
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ReminderSettingItem */
        ReminderSettingItem: {
            progress_status: components["schemas"]["ProgressStatus"];
            /** Reminder Days */
            reminder_days: number;
            /** Is Default */
            is_default: boolean;
        };
        /** ReminderSettingWrite */
        ReminderSettingWrite: {
            progress_status: components["schemas"]["ProgressStatus"];
            /** Reminder Days */
            reminder_days: number;
        };
        /** ReminderSettingsRead */
        ReminderSettingsRead: {
            /** Settings */
            settings: components["schemas"]["ReminderSettingItem"][];
        };
        /** ReminderSettingsUpdate */
        ReminderSettingsUpdate: {
            /** Settings */
            settings: components["schemas"]["ReminderSettingWrite"][];
        };
        /** ReportResponse */
        ReportResponse: {
            /** Month */
            month: string;
            /** Rows */
            rows: components["schemas"]["ReportRow"][];
            /** Total Hours */
            total_hours: number;
            /** Total Amount Estimated */
            total_amount_estimated?: number | null;
        };
        /** ReportRow */
        ReportRow: {
            /** Client Id */
            client_id: string;
            /** Client Name */
            client_name: string;
            /** Client Color */
            client_color: string;
            /** Hours */
            hours: number;
            /** Events Count */
            events_count: number;
            /** Amount Estimated */
            amount_estimated?: number | null;
        };
        /** ResendVerificationRequest */
        ResendVerificationRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ShareCreate */
        ShareCreate: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** @default viewer */
            role: components["schemas"]["ShareRole"];
        };
        /** ShareRead */
        ShareRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Calendar Id
             * Format: uuid
             */
            calendar_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            role: components["schemas"]["ShareRole"];
        };
        /**
         * ShareRole
         * @enum {string}
         */
        ShareRole: "owner" | "editor" | "viewer";
        /** SlotSuggestion */
        SlotSuggestion: {
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
        };
        /**
         * StudentCategory
         * @enum {string}
         */
        StudentCategory: "compta" | "rh" | "bf" | "formation_courte";
        /** StudentNoteCreate */
        StudentNoteCreate: {
            /** Note */
            note: string;
        };
        /** StudentNoteRead */
        StudentNoteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Student Profile Id
             * Format: uuid
             */
            student_profile_id: string;
            /** Note */
            note: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
        };
        /** StudentProfileRead */
        StudentProfileRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Formation Id
             * Format: uuid
             */
            formation_id: string;
            category: components["schemas"]["StudentCategory"];
            /**
             * Inscription Date
             * Format: date
             */
            inscription_date: string;
            /**
             * Access Start Date
             * Format: date
             */
            access_start_date: string;
            /**
             * Access End Date
             * Format: date
             */
            access_end_date: string;
            /** Exam Date */
            exam_date: string | null;
            payment_status: components["schemas"]["PaymentStatus"];
            learner_status: components["schemas"]["LearnerStatus"];
            progress_status: components["schemas"]["ProgressStatus"];
            /**
             * Risk Color
             * @default
             */
            risk_color: string;
            /** Alert Enabled */
            alert_enabled: boolean;
            /** Onboarding Done */
            onboarding_done: boolean;
            /** Followup Date */
            followup_date: string | null;
            /** Exam Blank Done */
            exam_blank_done: boolean;
            /** Final Exam Done */
            final_exam_done: boolean;
            /** End Training Done */
            end_training_done: boolean;
            /** Testimonial Requested */
            testimonial_requested: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StudentProfileWrite */
        StudentProfileWrite: {
            /** Formation Id */
            formation_id?: string | null;
            category?: components["schemas"]["StudentCategory"] | null;
            /** Inscription Date */
            inscription_date?: string | null;
            /** Access Start Date */
            access_start_date?: string | null;
            /** Access End Date */
            access_end_date?: string | null;
            /** Exam Date */
            exam_date?: string | null;
            payment_status?: components["schemas"]["PaymentStatus"] | null;
            learner_status?: components["schemas"]["LearnerStatus"] | null;
            progress_status?: components["schemas"]["ProgressStatus"] | null;
            /** Alert Enabled */
            alert_enabled?: boolean | null;
            /** Onboarding Done */
            onboarding_done?: boolean | null;
            /** Followup Date */
            followup_date?: string | null;
            /** Exam Blank Done */
            exam_blank_done?: boolean | null;
            /** Final Exam Done */
            final_exam_done?: boolean | null;
            /** End Training Done */
            end_training_done?: boolean | null;
            /** Testimonial Requested */
            testimonial_requested?: boolean | null;
        };
        /** StudentRead */
        StudentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Status */
            status: string;
            profile?: components["schemas"]["StudentProfileRead"] | null;
        };
        /** SyncAlertSheetResponse */
        SyncAlertSheetResponse: {
            /** Synced */
            synced: number;
            /** Failed */
            failed: number;
            /** Not Configured */
            not_configured: boolean;
        };
        /** TaskCreate */
        TaskCreate: {
            /** Client Id */
            client_id?: string | null;
            /** Title */
            title: string;
            /** Category */
            category?: string | null;
            /** @default pas_urgent */
            priority: components["schemas"]["TaskPriority"];
            /**
             * Stars
             * @default 1
             */
            stars: number;
            /** Due Date */
            due_date?: string | null;
            /** @default a_faire */
            status: components["schemas"]["TaskStatus"];
            /** Note */
            note?: string | null;
        };
        /**
         * TaskPriority
         * @enum {string}
         */
        TaskPriority: "urgent" | "pas_urgent";
        /** TaskRead */
        TaskRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Client Id */
            client_id: string | null;
            /**
             * Owner User Id
             * Format: uuid
             */
            owner_user_id: string;
            /** Title */
            title: string;
            /** Category */
            category: string | null;
            priority: components["schemas"]["TaskPriority"];
            /** Stars */
            stars: number;
            /** Due Date */
            due_date: string | null;
            status: components["schemas"]["TaskStatus"];
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "a_faire" | "en_cours" | "fait" | "reporte";
        /** TaskUpdate */
        TaskUpdate: {
            /** Client Id */
            client_id?: string | null;
            /** Title */
            title?: string | null;
            /** Category */
            category?: string | null;
            priority?: components["schemas"]["TaskPriority"] | null;
            /** Stars */
            stars?: number | null;
            /** Due Date */
            due_date?: string | null;
            status?: components["schemas"]["TaskStatus"] | null;
            /** Note */
            note?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Timezone */
            timezone: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidCredentialsError"];
                };
            };
            /** @description Email not verified */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailNotVerifiedError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Invalid or expired token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidOrExpiredTokenError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calendars_calendars_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarRead"][];
                };
            };
        };
    };
    create_calendar_calendars_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_calendars__calendar_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendar_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_calendar_calendars__calendar_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendar_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_calendar_calendars__calendar_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendar_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_calendar_calendars__calendar_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendar_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_clients_get: {
        parameters: {
            query?: {
                client_type?: components["schemas"]["ClientType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_clients_clients_search_get: {
        parameters: {
            query?: {
                email?: string | null;
                telephone?: string | null;
                nom?: string | null;
                prenom?: string | null;
                inscription_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_agenda_clients__client_id__agenda_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_clients__client_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_events_get: {
        parameters: {
            query: {
                from_utc: string;
                to_utc: string;
                calendar_ids?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_events__event_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_event_events__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_conflicts_events_check_conflicts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckConflictsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_availability_availability_get: {
        parameters: {
            query: {
                from_utc: string;
                to_utc: string;
                duration_min?: number;
                calendar_ids: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suggestions_suggestions_get: {
        parameters: {
            query: {
                event_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_dashboard_get: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_reports_get: {
        parameters: {
            query: {
                month: string;
                client_type?: components["schemas"]["ClientType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_students_students_get: {
        parameters: {
            query?: {
                learner_status?: components["schemas"]["LearnerStatus"] | null;
                progress_status?: components["schemas"]["ProgressStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reminder_settings_students_reminder_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderSettingsRead"];
                };
            };
        };
    };
    update_reminder_settings_students_reminder_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderSettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_profile_students__client_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_student_profile_students__client_id__profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentProfileWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_student_notes_students__client_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentNoteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_student_note_students__client_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentNoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentNoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"] | null;
                priority?: components["schemas"]["TaskPriority"] | null;
                client_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_formations_formations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormationRead"][];
                };
            };
        };
    };
    generate_alerts_cron_generate_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateAlertsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateAlertsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_task_alerts_cron_generate_task_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateAlertsResponse"];
                };
            };
        };
    };
    generate_followup_alerts_cron_generate_followup_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateAlertsResponse"];
                };
            };
        };
    };
    sync_alert_sheet_cron_sync_alert_sheet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncAlertSheetResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
